package com.spot69.model;

public enum Permissions {
    // Utilisateurs
    GESTION_COMPTES,
    SUPPRESSION_COMPTES,
    GESTION_ROLES_ET_PERMISSIONS,

    // Commandes
    GESTION_COMMANDES,
    SUPPRESSION_COMMANDES,
    VALIDATION_COMMANDES,
    MODIFIER_STATUT_COMMANDES,
    PLACER_DES_COMMANDES,
    VOIR_HISTORIQUE_COMMANDES,

    // Approvisionnement & Inventaire
    GESTION_FOURNISSEURS,
    SUPPRESSION_FOURNISSEURS,
    GESTION_FACTURES,
    SUPPRESSION_FACTURES,
    GESTION_STOCK,

    // Produits
    GESTION_PRODUITS,
    SUPPRESSION_PRODUITS,
    GESTION_CATEGORIES_SOUS_CATEGORIES,
    SUPPRESSION_CATEGORIES_SOUS_CATEGORIES,
    VOIR_LES_PRODUITS,

    // Rayons, Catégories, Sous-catégories
    GESTION_RAYONS_CATEGORIES_SOUS_CATEGORIES,
    SUPPRESSION_RAYONS_CATEGORIES_SOUS_CATEGORIES,

    // Menu
    GESTION_MENU_CATEGORIES,
    SUPPRESSION_MENU_CATEGORIES,
    GESTION_PLATS,
    SUPPRESSION_PLATS,
    VOIR_LE_MENU,

    // Ventes et Rapports
    VOIR_HISTORIQUES_COMMANDES,
    VOIR_RAPPORT_CAISSE,
    VOIR_RAPPORT_PAR_PRODUITS,

    // Gestion des tables rooftop
    GESTION_TABLES_ROOFTOP,
    SUPPRESSION_TABLES_ROOFTOP,

    // Événements
    GESTION_EVENEMENTS,
    SUPPRESSION_EVENEMENTS
}